### ISSUE TITLE
AudioRecorder[14138:319458] -[NSNull renderingMode]: unrecognized selector sent to instance 0x7fff8e4e4c00 (lldb) 

### ISSUE THREAD

**Issue by ifehrim** [patrickgue/AudioRecorder#1]
Hi when i run the app, this problem show, idon't know how to solve this issue::

`2020-03-25 22:08:28.652382+0800 AudioRecorder[14138:319458] -[NSNull renderingMode]: unrecognized selector sent to instance 0x7fff8e4e4c00
(lldb) `

Thanks

**Comment by patrickgue** [comment]
Probably wasn't able to load the custom font. I committed an updated version just using the system font.

Try building and running this new version. Unfortunately I wont be able to help you any further, as I don't really have time to give support for my hobby projects ;)

Still I'm glad, that people are interested in them!
